// GENERATED by scripts/verify-onchain.mjs from the on-chain Anchor IDLs.
// Do not edit by hand; run `npm run verify:onchain` to refresh.
export const PROGRAM_ERRORS = {
  "6000": {
    "name": "NotAuthorized",
    "msg": "The given account is not authorized to execute this instruction.",
    "program": "pump"
  },
  "6001": {
    "name": "AlreadyInitialized",
    "msg": "The program is already initialized.",
    "program": "pump"
  },
  "6002": {
    "name": "TooMuchSolRequired",
    "msg": "slippage: Too much SOL required to buy the given amount of tokens.",
    "program": "pump"
  },
  "6003": {
    "name": "TooLittleSolReceived",
    "msg": "slippage: Too little SOL received to sell the given amount of tokens.",
    "program": "pump"
  },
  "6004": {
    "name": "MintDoesNotMatchBondingCurve",
    "msg": "The mint does not match the bonding curve.",
    "program": "pump"
  },
  "6005": {
    "name": "BondingCurveComplete",
    "msg": "The bonding curve has completed and liquidity migrated to raydium.",
    "program": "pump"
  },
  "6006": {
    "name": "BondingCurveNotComplete",
    "msg": "The bonding curve has not completed.",
    "program": "pump"
  },
  "6007": {
    "name": "NotInitialized",
    "msg": "The program is not initialized.",
    "program": "pump"
  },
  "6008": {
    "name": "WithdrawTooFrequent",
    "msg": "Withdraw too frequent",
    "program": "pump"
  },
  "6009": {
    "name": "NewSizeShouldBeGreaterThanCurrentSize",
    "msg": "new_size should be > current_size",
    "program": "pump"
  },
  "6010": {
    "name": "AccountTypeNotSupported",
    "msg": "Account type not supported",
    "program": "pump"
  },
  "6011": {
    "name": "InitialRealTokenReservesShouldBeLessThanTokenTotalSupply",
    "msg": "initial_real_token_reserves should be less than token_total_supply",
    "program": "pump"
  },
  "6012": {
    "name": "InitialVirtualTokenReservesShouldBeGreaterThanInitialRealTokenReserves",
    "msg": "initial_virtual_token_reserves should be greater than initial_real_token_reserves",
    "program": "pump"
  },
  "6013": {
    "name": "FeeBasisPointsGreaterThanMaximum",
    "msg": "fee_basis_points greater than maximum",
    "program": "pump"
  },
  "6014": {
    "name": "AllZerosWithdrawAuthority",
    "msg": "Withdraw authority cannot be set to System Program ID",
    "program": "pump"
  },
  "6015": {
    "name": "PoolMigrationFeeShouldBeLessThanFinalRealSolReserves",
    "msg": "pool_migration_fee should be less than final_real_sol_reserves",
    "program": "pump"
  },
  "6016": {
    "name": "PoolMigrationFeeShouldBeGreaterThanCreatorFeePlusMaxMigrateFees",
    "msg": "pool_migration_fee should be greater than creator_fee + MAX_MIGRATE_FEES",
    "program": "pump"
  },
  "6017": {
    "name": "DisabledWithdraw",
    "msg": "Migrate instruction is disabled",
    "program": "pump"
  },
  "6018": {
    "name": "DisabledMigrate",
    "msg": "Migrate instruction is disabled",
    "program": "pump"
  },
  "6019": {
    "name": "InvalidCreator",
    "msg": "Invalid creator pubkey",
    "program": "pump"
  },
  "6020": {
    "name": "BuyZeroAmount",
    "msg": "Buy zero amount",
    "program": "pump"
  },
  "6021": {
    "name": "NotEnoughTokensToBuy",
    "msg": "Not enough tokens to buy",
    "program": "pump"
  },
  "6022": {
    "name": "SellZeroAmount",
    "msg": "Sell zero amount",
    "program": "pump"
  },
  "6023": {
    "name": "NotEnoughTokensToSell",
    "msg": "Not enough tokens to sell",
    "program": "pump"
  },
  "6024": {
    "name": "Overflow",
    "msg": "Overflow",
    "program": "pump"
  },
  "6025": {
    "name": "Truncation",
    "msg": "Truncation",
    "program": "pump"
  },
  "6026": {
    "name": "DivisionByZero",
    "msg": "Division by zero",
    "program": "pump"
  },
  "6027": {
    "name": "NotEnoughRemainingAccounts",
    "msg": "Not enough remaining accounts",
    "program": "pump"
  },
  "6028": {
    "name": "AllFeeRecipientsShouldBeNonZero",
    "msg": "All fee recipients should be non-zero",
    "program": "pump"
  },
  "6029": {
    "name": "UnsortedNotUniqueFeeRecipients",
    "msg": "Unsorted or not unique fee recipients",
    "program": "pump"
  },
  "6030": {
    "name": "CreatorShouldNotBeZero",
    "msg": "Creator should not be zero",
    "program": "pump"
  },
  "6031": {
    "name": "StartTimeInThePast",
    "msg": null,
    "program": "pump"
  },
  "6032": {
    "name": "EndTimeInThePast",
    "msg": null,
    "program": "pump"
  },
  "6033": {
    "name": "EndTimeBeforeStartTime",
    "msg": null,
    "program": "pump"
  },
  "6034": {
    "name": "TimeRangeTooLarge",
    "msg": null,
    "program": "pump"
  },
  "6035": {
    "name": "EndTimeBeforeCurrentDay",
    "msg": null,
    "program": "pump"
  },
  "6036": {
    "name": "SupplyUpdateForFinishedRange",
    "msg": null,
    "program": "pump"
  },
  "6037": {
    "name": "DayIndexAfterEndIndex",
    "msg": null,
    "program": "pump"
  },
  "6038": {
    "name": "DayInActiveRange",
    "msg": null,
    "program": "pump"
  },
  "6039": {
    "name": "InvalidIncentiveMint",
    "msg": null,
    "program": "pump"
  },
  "6040": {
    "name": "BuyNotEnoughSolToCoverRent",
    "msg": "Buy: Not enough SOL to cover for rent exemption.",
    "program": "pump"
  },
  "6041": {
    "name": "BuyNotEnoughSolToCoverFees",
    "msg": "Buy: Not enough SOL to cover for fees.",
    "program": "pump"
  },
  "6042": {
    "name": "BuySlippageBelowMinTokensOut",
    "msg": "Slippage: Would buy less tokens than expected min_tokens_out",
    "program": "pump"
  },
  "6043": {
    "name": "NameTooLong",
    "msg": null,
    "program": "pump"
  },
  "6044": {
    "name": "SymbolTooLong",
    "msg": null,
    "program": "pump"
  },
  "6045": {
    "name": "UriTooLong",
    "msg": null,
    "program": "pump"
  },
  "6046": {
    "name": "CreateV2Disabled",
    "msg": null,
    "program": "pump"
  },
  "6047": {
    "name": "CpitializeMayhemFailed",
    "msg": null,
    "program": "pump"
  },
  "6048": {
    "name": "MayhemModeDisabled",
    "msg": null,
    "program": "pump"
  },
  "6049": {
    "name": "CreatorMigratedToSharingConfig",
    "msg": "creator has been migrated to sharing config, use pump_fees::reset_fee_sharing_config instead",
    "program": "pump"
  },
  "6050": {
    "name": "UnableToDistributeCreatorVaultMigratedToSharingConfig",
    "msg": "creator_vault has been migrated to sharing config, use pump:distribute_creator_fees instead",
    "program": "pump"
  },
  "6051": {
    "name": "SharingConfigNotActive",
    "msg": "Sharing config is not active",
    "program": "pump"
  },
  "6052": {
    "name": "UnableToDistributeCreatorFeesToExecutableRecipient",
    "msg": "The recipient account is executable, so it cannot receive lamports, remove it from the team first",
    "program": "pump"
  },
  "6053": {
    "name": "BondingCurveAndSharingConfigCreatorMismatch",
    "msg": "Bonding curve creator does not match sharing config",
    "program": "pump"
  },
  "6054": {
    "name": "ShareholdersAndRemainingAccountsMismatch",
    "msg": "Remaining accounts do not match shareholders, make sure to pass exactly the same pubkeys in the same order",
    "program": "pump"
  },
  "6055": {
    "name": "InvalidShareBps",
    "msg": "Share bps must be greater than 0",
    "program": "pump"
  },
  "6056": {
    "name": "CashbackNotEnabled",
    "msg": "Cashback is not enabled",
    "program": "pump"
  },
  "6057": {
    "name": "BuybackFeeRecipientNotAuthorized",
    "msg": "Buyback fee recipient not authorized",
    "program": "pump"
  },
  "6058": {
    "name": "AllBuybackFeeRecipientsShouldBeNonZero",
    "msg": null,
    "program": "pump"
  },
  "6059": {
    "name": "NotUniqueBuybackFeeRecipients",
    "msg": null,
    "program": "pump"
  },
  "6060": {
    "name": "BuybackBasisPointsOutOfRange",
    "msg": "buyback_basis_points must be <= 10_000",
    "program": "pump"
  },
  "6061": {
    "name": "WrongBuybackFeeRecipientsCount",
    "msg": "buyback fee recipients require exactly 8 remaining accounts (or none)",
    "program": "pump"
  },
  "6062": {
    "name": "BuybackFeeRecipientMissing",
    "msg": null,
    "program": "pump"
  },
  "6063": {
    "name": "UnsupportedQuoteMint",
    "msg": "Unsupported quote mint",
    "program": "pump"
  },
  "6064": {
    "name": "InvalidQuoteTokenProgram",
    "msg": "Create v2: quote token program must be legacy SPL Token",
    "program": "pump"
  },
  "6065": {
    "name": "InvalidAssociatedQuoteBondingCurve",
    "msg": "Create v2: associated quote bonding curve address does not match derivation",
    "program": "pump"
  },
  "6066": {
    "name": "QuoteMintWhitelistFull",
    "msg": "Quote mint whitelist is full",
    "program": "pump"
  },
  "6067": {
    "name": "QuoteMintAlreadyWhitelisted",
    "msg": "Quote mint is already whitelisted",
    "program": "pump"
  },
  "6068": {
    "name": "QuoteMintNotWhitelisted",
    "msg": "Quote mint is not in the whitelist",
    "program": "pump"
  },
  "6069": {
    "name": "QuoteMintNotEligibleForWhitelist",
    "msg": "Quote mint cannot be added or removed via whitelist (default or native SOL mint)",
    "program": "pump"
  },
  "6070": {
    "name": "UnableToDistributeCreatorFeesToUninitializedAccount",
    "msg": "Unable to distribute creator fees to uninitialized account",
    "program": "pump"
  },
  "6071": {
    "name": "MayhemModeQuoteMintNotAllowed",
    "msg": "Mayhem mode quote mint not allowed",
    "program": "pump"
  }
};
